pull_request_rules:
  - name: merge scala-steward PRs
    conditions:
      - "author=scala-steward"
      - "status-success=jdk-11 Build and Tests"
      - "status-success=jdk-17 Build and Tests"
    actions:
      merge:
        method: squash
