addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "1.15")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.5.1")
addSbtPlugin("com.codacy"        % "sbt-codacy-coverage" % "1.3.11")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "2.0.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"         % "0.5.2")