addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.13.0")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.9.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.3")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.2.2")
