addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.3.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"  % "1.2.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"    % "4.0.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.6")
